version: "3.2"
services:

  database:
    image: 'postgres:14'
    container_name: 'survey_django'

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5434:5432
    restart: always
    
    volumes:
      - ./.database_data:/var/lib/postgresql/data
