# Generated by Django 4.0.4 on 2022-07-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='survey_id',
            new_name='survey',
        ),
    ]
