# Generated by Django 4.0.4 on 2022-07-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_rename_question_id_answer_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Choice',
        ),
    ]
