# Generated by Django 4.0.4 on 2022-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0006_alter_answer_id_alter_choice_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default='available', max_length=32)),
            ],
        ),
    ]
