# Generated by Django 4.0.4 on 2022-07-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0007_choicesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesmodel',
            name='status',
            field=models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default=None, max_length=32),
        ),
    ]
