# Generated by Django 4.0.4 on 2022-07-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0008_alter_choicesmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicesmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='choicesmodel',
            name='choice',
            field=models.CharField(choices=[('<function GetOpts.get_opts.<locals>.<lambda> at 0x00000143E1984A60>', '<function GetOpts.get_opts.<locals>.<lambda> at 0x00000143E1984A60>')], default=None, max_length=200),
        ),
    ]
