# Generated by Django 4.0.4 on 2022-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0010_alter_choicesmodel_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesmodel',
            name='choice',
            field=models.CharField(max_length=200),
        ),
    ]
