# Generated by Django 4.0.4 on 2022-07-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0013_alter_choicesmodel_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.question')),
            ],
        ),
        migrations.DeleteModel(
            name='ChoicesModel',
        ),
    ]
