# Generated by Django 4.0.4 on 2022-07-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0014_votesmodel_delete_choicesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VotesModel',
        ),
    ]
