# Generated by Django 4.0.4 on 2022-07-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0015_delete_votesmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choices',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='survey',
            table='surveys',
        ),
    ]
